### ISSUE TITLE
please regist latest version to webjar classic

### ISSUE THREAD

**Issue by dongully** [webjars/jquery-i18n-properties#2]
in webjar classic's latest version 1.10.2 and bower's latetest version 1.2.0, loadAndParseFile method is always async to false.

<pre>
function loadAndParseFile(filename, settings) {
    $.ajax({
        url:        filename,
        async:      false,
        cache:      settings.cache,
        contentType:'text/plain;charset='+ settings.encoding,
        dataType:   'text',
        success:    function(data, status) {
                        parseData(data, settings.mode); 
                    }
    });
}
</pre>

but in github's latest code, reference setting.async.

<pre>
function loadAndParseFile(filename, settings) {
    $.ajax({
        url: filename,
        async: settings.async,
        cache: settings.cache,
        dataType: 'text',
        success: function (data, status) {
        parseData(data, settings.mode);
            callbackIfComplete(settings);
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log('Failed to download or parse ' + filename);
            callbackIfComplete(settings);
        }
    });
}
</pre>

**Comment by jamesward** [comment]
Which version do you need?

**Comment by dongully** [comment]
I want a async true version, but have not released yet, so post new issue.

https://github.com/jquery-i18n-properties/jquery-i18n-properties/issues/33

**Comment by jamesward** [comment]
Once there is a new release we can create a new version of the WebJar.

**Comment by dongully** [comment]
New version has released, please create a new version of the WebJar.

https://github.com/jquery-i18n-properties/jquery-i18n-properties/releases/tag/1.2.2
